# Site settings
title: Ben Schwab
email:
description: > # this means to ignore newlines until "baseurl:"
  Ben Schwab. Software Developer. Random thoughts on Android, Programming, and life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: BenSchwab13
github_username:  BenSchwab

# Build settings
markdown: kramdown
